FROM node:18-bullseye

RUN apt-get update && apt-get install -y \
    python3 \
    build-essential \
    libnss3-dev \
    libatk-bridge2.0-dev \
    libgtk-3-0 \
    squashfs-tools \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .
RUN npm ci
RUN npm run transpile:electron
RUN npm run build
RUN npm run dist:linux