name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build for ${{ matrix.os }}
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            npm run dist:win
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            npm run dist:mac
          else
            npm run dist:linux
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: dist/
          retention-days: 1

  create-release:
    needs: release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/dist-windows-latest/**/*.exe
            dist/dist-windows-latest/**/*.msi
            dist/dist-macos-latest/**/*.dmg
            dist/dist-ubuntu-latest/**/*.AppImage
            dist/dist-ubuntu-latest/**/*.deb
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
